### ISSUE TITLE
slow motion crashed k20

### ISSUE THREAD

**Issue by khalednabawy** [Urnyx05/GCam-translations#12]
hello,
the slow motion mode crashed with k20 or mi 9t,
there is no error but the app will close
thanks.

**Comment by Urnyx05** [comment]
Slow motion doesn't work at all on Mi9/9T/9T Pro. Anyway, this isn't the place where to report GCam bugs because it's made only for translations

**Comment by khalednabawy** [comment]
ok thanks :)
